version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: export PYTHONPATH=$PYTHONPATH:$(pwd)
      - run:
          command: cd covid_surge/tests && py.test *.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
