version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: test
          command: |
              # pytest dep in requirements.txt file
              cd covid_surge/tests
              python3/pytest

workflows:
  main:
    jobs:
      - build-and-test
