version: 2.1

workflows:
  version: 2
  build_deploy:
    jobs:
      - build

jobs:
  build:

    docker:
      - image: circleci/python:3.7.5

    steps:
      - checkout
      - run:
          name: Requirements install
          command: |
              sudo pip install --upgrade pip
              sudo pip install -U -r requirements.txt
              echo " "
              echo "requirements installed"
              echo " "
              export PYTHONPATH=$PYTHONPATH:$(pwd)
              pytest --cov=./
              #bash <(curl -s https://codecov.io/bash) 
              codecov
